name: 'Set environment variables'
description: 'Configures environment variables for workflows'
inputs:
  varFilePath:
    description: 'Default path to variables directory.'
    required: false
    default: ./.github/variables/*
runs:
  using: "composite"
  steps:
    - run: |
        sed "" ${{ inputs.varFilePath }} >> $GITHUB_ENV
      shell: bash
