name: Deploy infrastructure
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Set Environment Variables
        uses: ./.github/actions/setvars
        with:
          varFilePath: ./.github/variables/variables.env
      - name: Setup prerequisites
        run:  |
          cd scripts
          aws sts get-caller-identity | cat
           aws configure list 
          sh prerequisites.sh
      - name: Run terraform
        run:  |
          cd infrastructure
          terraform init -backend-config=./config.s3.tfbackend
          terraform apply -auto-approve
